### ISSUE TITLE
website 404s

### ISSUE THREAD

**Issue by JohnDDuncanIII** [tpgillam/cuneifyplus#4]
https://oracc.museum.upenn.edu/cuneifyplus/

<img width="1392" alt="Screenshot 2024-10-14 at 3 50 50 AM" src="https://github.com/user-attachments/assets/e9b0dd70-9967-4744-9d7f-501886e54f79">

http://oracc.iaas.upenn.edu/cuneifyplus

also doesn't work anymore

**Comment by tpgillam** [comment]
Thanks for pointing this out! 

I'm not actively maintaining this project any more. But Andrew Senior rewrote it in javascript and added some great features, so I recommend you check it out:
- https://andrewsenior.com/cuneify/index.html 
- https://github.com/asenior/cuneify
